### ISSUE TITLE
wrong / lack of .ini file syntax highlighting 

### ISSUE THREAD

**Issue by jkozniewski** [VirtualWhirlwind/vscode-povray2#12]
There seem to be no proper syntax highlighting for the *.ini files so it's either a bug or a feature request to add it :)

![Screenshot 2022-03-19 at 12 24 08](https://user-images.githubusercontent.com/6979983/159119163-cd65a786-fcf3-474a-b7cf-415ff6e582b2.jpg)

**Comment by bentorkington** [comment]
Looks like the plugin tries to interpret `.INI` files as if they were Povray source. Probably best in the short term if the `.INI` suffix is removed so it falls back on the more general syntax highlighting for that format

**Comment by jkozniewski** [comment]
Thanks - is there any way I can help to create proper syntax highlight for this type of files (never done VS Code extension stuff but with some tips I might contribute a patch as it's probably mostly generating some json with proper keywords) ?

**Comment by bentorkington** [comment]
Because `.ini` is a popular format outside of Povray, there are already extensions to handle its grammar.

You could add Povray's specific keywords as snippets or code suggestions, but at this point I also don't know whether this would augment or override existing `.ini` parser extensions.

The most convenient feature I can think of would be a code snippet that generates a sample Povray `.ini` file similar to what you've posted above (probably with all the modifiers except `Width` and `Height` commented out) as a helpful starting point.

**Comment by jkozniewski** [comment]
oh.. ok.. you're right that `.ini` is generic file format so just installed this extension - https://marketplace.visualstudio.com/items?itemName=DavidWang.ini-for-vscode and changed file association manually :) Thanks !

**Comment by kennebel** [comment]
Pulled out ini from the file types this extension will try to handle.

**Comment by bentorkington** [comment]
@kennebel , I had a PR for this and #15 already open if you think that they'll save you time?

**Comment by kennebel** [comment]
Sorry for missing that. Reviewing the PR's now.
